server:
  port: 8090
  context-path: /sso-client2
security:
  oauth2:
    client:
      client-id: client2
      client-secret: clientSecret2
      user-authorization-uri: http://localhost:9999/sso-server/oauth/authorize
      access-token-uri: http://localhost:9999/sso-server/oauth/token
    resource:
      jwt:
        key-uri: http://localhost:9999/sso-server/oauth/token_key